# Generated by Django 4.0.1 on 2022-04-13 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fac_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('honorific', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'title',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('lec_description', models.TextField(blank=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.faculty')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.title')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecture',
                'managed': True,
            },
        ),
    ]
