# Generated by Django 4.0.1 on 2022-04-13 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conceptual',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('conceptual_dif', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'conceptual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('programming_dif', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'programming',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'skill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('technical_dif', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'technical',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Skill', models.ManyToManyField(blank=True, related_name='pskills', to='projects.Skill')),
                ('conceptual', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.conceptual')),
                ('lecture', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lecture')),
                ('lecture2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programming', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.programming')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.status')),
                ('subject', models.ManyToManyField(blank=True, related_name='psubjects', to='projects.Subjects')),
                ('technical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.technical')),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
    ]
